
name: build

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradle-project/gradlew

      - name: Run Tests
        run: ./gradle-project/gradlew test

      - name: Run Test Coverage
        run: ./gradle-project/gradlew jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
            name: jacoco-report
            path: build/reports/jacoco/test/jacocoTestReport